### ISSUE TITLE
Apps submitted by the deleted "In Peers" still show up on "Queued/Pending Apps"

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#116]
@rrocchio @StillSlippery @alroman - On demo casa I deleted "Berkeley" from the "In Peers" config list but the apps from that sender still show up on "Queued/Pending Apps" with sender labeled as "removed.

Should we auto-delete the apps sent by the deleted "In Peer" from the "Queued/Pending Apps"?

![capture](https://cloud.githubusercontent.com/assets/1034174/18064974/bb15b77c-6de6-11e6-8f0d-7f3f79a53ac8.PNG)

**Comment by alroman** [comment]
I think the Rails app is not doing any cleanup when you remove peers.  There's probably a good reason for this and I can only guess it's because it would leave the app catalog in an inconsistent state if you were to propagate removals.  @rrocchio and @StillSlippery can probably shed more light on this.

**Comment by ctrance** [comment]
@alroman @StillSlippery @rrocchio - actually there's an old ticket for the same issue reported by Joshua https://github.com/ucla/casa-on-rails/issues/58

**Comment by StillSlippery** [comment]
#58 Duplicate of this issue.
