### ISSUE TITLE
I was able to submit without filling in any of the "App Launch" fields

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#165]
@uclanate I was able to submit an app without any App Launch data. I left Web App, iOS App and Android App fields blank. It's noted on the tab that the App Launch data is required.

**Comment by uclanate** [comment]
This is the expected behavior for now. If they leave all three blank we will repopulate the URL with the app catalog link.   However, I would like to add this validation if possible (I had trouble making it work). @krozett could you take a look at how you would approach adding a conditional validation for either url OR iOS launch details OR android launch details?

**Comment by krozett** [comment]
@uclanate You shouldn't need a validator though. It's ok if all 3 fields are blank. We can just display the app catalog link as the web URL.

**Comment by krozett** [comment]
So we decided that we do want this validation, but we should add some special cases for admins who want to bypass the validation. Mostly just for the special cases of apps that aren't in the catalog but we are using for hosting a privacy policy.

@uclanate To add this kind of validation I believe you have to add a custom validation method. That's not as hard as it sounds. I found an example on SO:
https://stackoverflow.com/a/26475458

Although the code is missing a crucial piece of info, how you tell the model to call the validator method. See below:
https://guides.rubyonrails.org/active_record_validations.html#custom-methods

**Comment by ctrance** [comment]
App launch is validating now.
