### ISSUE TITLE
CASA opens app to the store instead of opening the installed app

### ISSUE THREAD

**Issue by ctrance** [ucla-oarc-mobile/casa-on-rails#183]
@uclanate When you tap "iOS" under App Details section of BruinXperience App Edited, CASA take the user to the store instead of opening the installed app.

**Comment by ctrance** [comment]
@uclanate Same thing happens on Android, CASA does not launch the app if it's installed. It always take the user to the app store.

**Comment by uclanate** [comment]
This is expected behavior for the App Catalog. To launch apps from a client (e.g. UCLA Mobile) go to that app that has a launch dashboard. This is just a Catalog of apps (CASA provider) not a launch dashboard (CASA consumer). To install and launch apps to a client, use either UCLA Mobile or apps.ucla.edu/mobile.

Closing this issue.
