### ISSUE TITLE
Something in the CASA on Rails launch is making MWF built sites too wide

### ISSUE THREAD

**Issue by rrocchio** [ucla-oarc-mobile/casa-on-rails#40]
This is happening in 4 sites:

1) The Library
2) Dining
3) The Bruin Bus
## 4) Anderson

Chris is going to try to look at this and see if she can share any insights... but then she is on vacation for the next 4 days....

**Comment by spiritcapsule** [comment]
So we're only seeing this on some sites, not all sites with MWF. We're seeing the anomaly of display being too wide on iPhones with iOS 8.3 (mine is a 5s). But it looks fine on Android (Kitkat 4.4.4) Droid Turbo. Looks fine on desktop browsers.

**Comment by spiritcapsule** [comment]
Anderson is not using MWF.

**Comment by spiritcapsule** [comment]
For comparison, these sites are known good - they do not exhibit pages too wide.
Newsroom
Directory
Map
Happenings
Recreation

Known bad version - they do exhibit pages too wide.
Library
Dining
Bruin Bus
Campus Tour

Library, Dining, Bruin Bus, and Campus Tour all use this viewport tag:
`<meta name="viewport" content="height=device-height,width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no;" />`

Research uses this viewport tag:
`<meta name="viewport" content="height=device-height,width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">`

Newsroom, Directory, Happenings, and Recreation use this viewport tag:
`<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">`

Map uses this viewport tag:
`<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />`

Library and Dining use this mwf css link:
http://m.ucla.edu/assets/css.php?

Bruin Bus uses this mwf css link:
http://m.ucla.edu/assets/css.php?theme=dropshadows

Campus Tour uses this mwf css link:
../assets/css.php?theme=dropshadows

Newsroom, Directory, and Map use this mwf css link:
http://m.ucla.edu/assets/css.php?lean

Happenings uses this mwf css link:
http://m.happenings.ucla.edu/assets/css.php?lean

Recreation uses this mwf css link:
assets/mwf.css

Research uses this mwf css link:
http://m.ucla.edu/assets/css.php?full=http://m.research.ucla.edu/css/research_full.css&standard=http://m.research.ucla.edu/css/research_standard.css

Chrome console on my desktop complains about the viewport tags in all cases where they use semicolons instead of commas to delineate the various specs. (Not sure why Map isn't displaying the too wide bug, other than maybe the spaces after the semicolons are helping.) All the ones that use semicolons should be changed to commas. (At least that's what Chrome says.) Also I'll note here that using max scale -1 is an accessibility issue.

**Comment by spiritcapsule** [comment]
My first guess would be to modify the viewport tags and see if that solves the issue. (I don't have a good way to make these changes or test them.)

**Comment by spiritcapsule** [comment]
So it looks like, for Campus Tour, these changes should be made in the UCLA mobile repo:
https://github.com/ucla/mobile
https://github.com/ucla/mobile/blob/master/root/tour/index.php

Maybe for Dining too???
https://github.com/ucla/mobile/blob/master/root/dining/header.php

I assume Library and Bruin Bus are maintained separately.
