### ISSUE TITLE
The Tags on the bottom of the UCLA wrapped label, need to have blue on them - looks funny

### ISSUE THREAD

**Issue by rrocchio** [ucla-oarc-mobile/casa-on-rails#77]
The Tags on the bottom of the UCLA wrapped label on casa.m.ucla.edu, need to have blue on them - the bottom of the wrapping logo, seems to be a tiny bit cut off.  The white letters bleed into the white background.

**Comment by laurencullen** [comment]
@rrocchio which device/browser are you using? Is it possible to send a screen shot? I don't see this issue.

![screen shot 2015-11-23 at 3 31 43 pm](https://cloud.githubusercontent.com/assets/13141571/11353390/7b0547a4-91f7-11e5-8de8-cad85395d6de.png)

**Comment by laurencullen** [comment]
@rrocchio @joshuaselsky see this issue on mobile device. Unfortunately, the logo cannot be controlled to show differently on mobile and media queries didn't work. So, I fixed it by changing to text UCLA instead of image based. It should show correctly on mobile and desktop now. Please let me know if you find any other issues. Thanks!

**Comment by jshslsky** [comment]
Closing because this has been fixed as described in the above comment.
